package com.bksoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttributeValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeValueAllPropertiesEquals(AttributeValue expected, AttributeValue actual) {
        assertAttributeValueAutoGeneratedPropertiesEquals(expected, actual);
        assertAttributeValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeValueAllUpdatablePropertiesEquals(AttributeValue expected, AttributeValue actual) {
        assertAttributeValueUpdatableFieldsEquals(expected, actual);
        assertAttributeValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeValueAutoGeneratedPropertiesEquals(AttributeValue expected, AttributeValue actual) {
        assertThat(actual)
            .as("Verify AttributeValue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeValueUpdatableFieldsEquals(AttributeValue expected, AttributeValue actual) {
        assertThat(actual)
            .as("Verify AttributeValue relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeValueUpdatableRelationshipsEquals(AttributeValue expected, AttributeValue actual) {
        assertThat(actual)
            .as("Verify AttributeValue relationships")
            .satisfies(a -> assertThat(a.getAttribute()).as("check attribute").isEqualTo(expected.getAttribute()))
            .satisfies(a -> assertThat(a.getVariant()).as("check variant").isEqualTo(expected.getVariant()));
    }
}
