package com.bksoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttributeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeAllPropertiesEquals(Attribute expected, Attribute actual) {
        assertAttributeAutoGeneratedPropertiesEquals(expected, actual);
        assertAttributeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeAllUpdatablePropertiesEquals(Attribute expected, Attribute actual) {
        assertAttributeUpdatableFieldsEquals(expected, actual);
        assertAttributeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeAutoGeneratedPropertiesEquals(Attribute expected, Attribute actual) {
        assertThat(actual)
            .as("Verify Attribute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeUpdatableFieldsEquals(Attribute expected, Attribute actual) {
        assertThat(actual)
            .as("Verify Attribute relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeUpdatableRelationshipsEquals(Attribute expected, Attribute actual) {
        // empty method
    }
}
